<!DOCTYPE html>
<html>
  <head>
    
    <meta charset="utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height, target-densitydpi=device-dpi" />
  

    <link rel="stylesheet" href="css/index.css"/>
    <link rel="stylesheet" href="css/font-awesome.css"/>
    <link rel="stylesheet" href="css/font.css"/>
    <link rel="stylesheet" href="css/ui.css"/>
    <script src="/js/zepto.js"></script>
    <script src="/js/index.js"></script>



  </head>
  <body>
    <div class="page">
      <div class="cont">
	<div class="head">

	  <div class="lock"> 
	  <span class="fa fa-lock"> </span>
	  </div>
	  
	 
	  <div class="logo">DUBNA</div>
       	  <div class="time"></div>
	  <div class="soda">SODA LABS</div>
	</div>
	<div class="temp">
	  23°C
          <br>
	  ≈27°C</div>
	<div class="menu">  
	   <div class="fa fa-map-marker do-checkin"> </div>
	</div>
	</div>
     	</div>
      <div class="bg">  
	</div>
      </div>

  </body>
</html>


