<!DOCTYPE html>
<html>
  <head>
    
    <meta charset="utf-8" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width, height=device-height, target-densitydpi=device-dpi" />
    <!--link rel="stylesheet" type="text/css" href="css/index.css" /-->
   

    <!--link rel="stylesheet" href="css/ui.css"-->
    <style>
      .page {
      width: 100%;
      height: 100vh;
}
      .cont {
      top: 0;
      left: 0;
      position: absolute;
      z-index: 2;
      width: 100%;
      height: 100vh;
}
      .head {
      background-color: blue;
      width: 100%;
      height: 140px;
}
      .menu {
      
}
      .bg {
      top: 0;
      left: 0;
      background-color: red;
      position: absolute;
      z-index: 0;
      width: 100%;
      height: 100vh;
      }
      </style>

  </head>
  <body>
    <div class="page">
      <div class="cont">
	<div class="head">
	  header
	</div>
	<div class="menu">
	  menu content
	</div>
	</div>
      <div class="bg">
	</div>
      </div>
  </body>
</html>


